-- TIPO ENUM PARA ROL DE USUARIO
CREATE TYPE ROL_USUARIO AS ENUM ('USUARIO', 'DUENO', 'ADMIN');

-- TABLA USUARIOS
CREATE TABLE USUARIOS (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROL ROL_USUARIO NOT NULL
);

-- TABLA RESTAURANTES
CREATE TABLE RESTAURANTES (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  DIRECCION VARCHAR(255),
  TELEFONO VARCHAR(15),
  IMAGEN_URL VARCHAR(255),
  ID_DUENO INT NOT NULL,
  FOREIGN KEY (ID_DUENO) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

-- TABLA CARTAS
CREATE TABLE CARTAS (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  FECHA_CREACION DATE DEFAULT CURRENT_DATE,
  IMAGEN_URL VARCHAR(255),
  ID_RESTAURANTE INT NOT NULL,
  FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID) ON DELETE CASCADE
);

-- TABLA PLATOS
CREATE TABLE PLATOS (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION TEXT,
  PRECIO DECIMAL(6,2) NOT NULL,
  CATEGORIA VARCHAR(50),
  ID_CARTA INT NOT NULL,
  FOREIGN KEY (ID_CARTA) REFERENCES CARTAS(ID) ON DELETE CASCADE
);

-- TABLA VALORACIONES
CREATE TABLE VALORACIONES (
  ID SERIAL PRIMARY KEY,
  PUNTUACION INT NOT NULL CHECK (PUNTUACION BETWEEN 1 AND 5),
  COMENTARIO TEXT,
  FECHA DATE DEFAULT CURRENT_DATE,
  ID_USUARIO INT NOT NULL,
  ID_RESTAURANTE INT NOT NULL,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID) ON DELETE CASCADE
);

ALTER TABLE VALORACIONES DROP COLUMN id_carta;

ALTER TABLE VALORACIONES ADD COLUMN id_carta INT REFERENCES cartas(id) ON DELETE CASCADE;

CREATE TABLE FAVORITOS (
  ID SERIAL PRIMARY KEY,
  ID_USUARIO INT NOT NULL,
  ID_CARTA INT NOT NULL,
  FECHA_AGREGADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_CARTA) REFERENCES CARTAS(ID) ON DELETE CASCADE,
  UNIQUE (ID_USUARIO, ID_CARTA) -- evita duplicados
);


CREATE TABLE categorias (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  id_carta INT NOT NULL REFERENCES cartas(id) ON DELETE CASCADE
);

ALTER TABLE platos DROP COLUMN categoria;

ALTER TABLE platos ADD COLUMN id_categoria INT REFERENCES categorias(id) ON DELETE CASCADE;

CREATE TABLE imagenes_carta (
  id SERIAL PRIMARY KEY,
  url TEXT NOT NULL,
  id_carta INT NOT NULL REFERENCES cartas(id) ON DELETE CASCADE
);

ALTER TABLE cartas DROP COLUMN imagen_url;

ALTER TABLE platos DROP COLUMN id_carta;

ALTER TABLE usuarios
ADD COLUMN "tokenRecuperacion" VARCHAR,
ADD COLUMN "tokenExpiracion" TIMESTAMP;


