-- TIPO ENUM PARA ROL DE USUARIO
CREATE TYPE ROL_USUARIO AS ENUM ('USUARIO', 'DUENO', 'ADMIN');

-- TABLA USUARIOS
CREATE TABLE USUARIOS (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROL ROL_USUARIO NOT NULL
);

-- TABLA RESTAURANTES
CREATE TABLE RESTAURANTES (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  DIRECCION VARCHAR(255),
  TELEFONO VARCHAR(15),
  IMAGEN_URL VARCHAR(255),
  ID_DUENO INT NOT NULL,
  FOREIGN KEY (ID_DUENO) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

-- TABLA CARTAS
CREATE TABLE CARTAS (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  FECHA_CREACION DATE DEFAULT CURRENT_DATE,
  IMAGEN_URL VARCHAR(255),
  ID_RESTAURANTE INT NOT NULL,
  FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID) ON DELETE CASCADE
);

-- TABLA PLATOS
CREATE TABLE PLATOS (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION TEXT,
  PRECIO DECIMAL(6,2) NOT NULL,
  CATEGORIA VARCHAR(50),
  ID_CARTA INT NOT NULL,
  FOREIGN KEY (ID_CARTA) REFERENCES CARTAS(ID) ON DELETE CASCADE
);

-- TABLA VALORACIONES
CREATE TABLE VALORACIONES (
  ID SERIAL PRIMARY KEY,
  PUNTUACION INT NOT NULL CHECK (PUNTUACION BETWEEN 1 AND 5),
  COMENTARIO TEXT,
  FECHA DATE DEFAULT CURRENT_DATE,
  ID_USUARIO INT NOT NULL,
  ID_RESTAURANTE INT NOT NULL,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID) ON DELETE CASCADE
);

CREATE TABLE FAVORITOS (
  ID SERIAL PRIMARY KEY,
  ID_USUARIO INT NOT NULL,
  ID_RESTAURANTE INT,
  ID_CARTA INT,
  ID_PLATO INT,
  FECHA_AGREGADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_CARTA) REFERENCES CARTAS(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_PLATO) REFERENCES PLATOS(ID) ON DELETE CASCADE,
  CHECK (
    (ID_RESTAURANTE IS NOT NULL)::INT +
    (ID_CARTA IS NOT NULL)::INT +
    (ID_PLATO IS NOT NULL)::INT = 1
  )
);

INSERT INTO "public".usuarios (nombre,email,"password",rol)
VALUES ('USUARIOPRUEBA', 'ejemplo@gmail.com', '1234','DUENO');

INSERT INTO "public".restaurantes (nombre,imagen_url,id_dueno)
VALUES ('RestaurantePrueba', 'https://ejemplo.com/img/carta-tapas.jpg', 1);

INSERT INTO "public".cartas (nombre,imagen_url,id_restaurante)
VALUES ('Carta de prueba', 'https://ejemplo.com/img/carta-tapas.jpg', 1);





